---
- hosts: all
  become: true
  tasks:
  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x' 

  - name: Crear directorio de trabajo
    file:
      path: /tmp/wordpress
      state: directory

  - name: Deploying docker-compose template
    template:
      src: /etc/ansible/wordpress.yml
      dest: /tmp/wordpress/wordpress.yml

  - name: Running docker-compose
    shell: /usr/local/bin/docker-compose -f /tmp/wordpress/wordpress.yml up -d
...